### PR TITLE
Get Raw Transactions Endpoint

### PR DESCRIPTION
**Pull request by zanuka**
POST can be made to the following endpoint:
http://127.0.0.1:9002/api/transactions/v1/getrawtransactions

BODY:
`{"transactions": [
    {"currency":  "NAV", "addresses": ["NW7uXr4ZAeJKigMGnKbSLfCBQY59cH1T8G", "NUDke42E3fwLqaBbBFRyVSTETuhWAi7ugk"]},
    {"currency":  "BTC",  "addresses": ["Bak7ahbZAA", "B91janABsa"]}
]}`

RESPONSE:
`{"data":{"results":[{"currency":"NAV","addresses":[{"address":"NW7uXr4ZAeJKigMGnKbSLfCBQY59cH1T8G","transactions":[{"txid":"11a7071a43a8da2b9ac116865a6cd92c985c3f7cbde63933d253f88dffaa311a","rawtx...`

### CODE REVIEW

**Comment by red010b37** [comment]
Can you delete all the other tests,

**Comment by red010b37** [comment]
Also can you update the depends or recreate it

**Comment by zanuka** [comment]
@red010b37 💾 fixed

**Comment by matt-auckland** [comment]
@ro-savage  Do you mean `{ data: [ this is an array of objects ] }` ?

**Comment by zanuka** [comment]
@ro-savage no reason really. will change it for you

**Pull request merged**
